name: finplus
description: FTL trading project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.1
  flutter_facebook_auth: ^5.0.7
  carousel_slider: ^4.1.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  firebase_remote_config: ^3.0.9
  cryptography_flutter: ^2.0.2

  ##internal packages
  commons:
      path: ./packages/commons
      
dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/pictures/