name: finplus
description: FTL trading project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2



  ##internal packages
  commons:
      path: ./packages/commons
      
dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true