name: finplus
description: FTL trading project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.4.1
  flutter_facebook_auth: ^5.0.7
  carousel_slider: ^4.1.1
  pull_to_refresh: ^2.0.0
  connectivity_plus: ^3.0.2
  internet_connection_checker: ^1.0.0+1
  firebase_remote_config: ^3.0.9
  cryptography_flutter: ^2.0.2
  cached_network_image: ^3.2.0
  intl: ^0.17.0
  photo_view: ^0.14.0
  file_picker: ^5.2.5
  flutter_linkify: ^5.0.2
  url_launcher: ^6.1.8
  flutter_slidable: ^2.0.0
  keyboard_actions: ^4.1.0
  flutter_inappwebview: ^5.7.2+3
  image_picker: ^0.8.6+1
  ##internal packages
  commons:
    path: ./packages/commons

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/pictures/
