name: finplus
description: FTL trading project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.4.2
  firebase_core: ^2.3.0
  flutter_facebook_auth: ^5.0.6
  carousel_slider: ^4.1.1
  pull_to_refresh: ^2.0.0

  ##internal packages
  commons:
      path: ./packages/commons
      
dev_dependencies:
  flutter_test:
    sdk: flutter






  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/icons/
  - assets/pictures/