// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6v9ShRHxs3kfYAmwJQghw15BAm8ZMDRQ',
    appId: '1:221459330613:web:d806d72159a6d19b2ca37c',
    messagingSenderId: '221459330613',
    projectId: 'ftl-finplus',
    authDomain: 'ftl-finplus.firebaseapp.com',
    storageBucket: 'ftl-finplus.appspot.com',
    measurementId: 'G-3WELD8TZ1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOEokFv5w507q2XKiQr9BY77e9_pHdYw',
    appId: '1:221459330613:android:f4fc6badba466a872ca37c',
    messagingSenderId: '221459330613',
    projectId: 'ftl-finplus',
    storageBucket: 'ftl-finplus.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwmJ2jGNWh_mCrZwqLQUUIXdbsIE4hkSU',
    appId: '1:221459330613:ios:3e766b08dc7dea822ca37c',
    messagingSenderId: '221459330613',
    projectId: 'ftl-finplus',
    storageBucket: 'ftl-finplus.appspot.com',
    iosClientId:
        '221459330613-ii04oria5usm339drlpq1kgb072el490.apps.googleusercontent.com',
    iosBundleId: 'com.ftl.finplus',
  );
}
