// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return android;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: 'AIzaSyDMD3W_xU8bfoOcgl1ChzTA1sCT_mQnI9g',
      authDomain: 'findata-8b973.firebaseapp.com',
      projectId: 'findata-8b973',
      storageBucket: 'findata-8b973.appspot.com',
      messagingSenderId: '94960442791',
      appId: '1:94960442791:web:410e7ea2f4bd9edf002a82',
      measurementId: 'G-VRF3QDH78Y');

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMD3W_xU8bfoOcgl1ChzTA1sCT_mQnI9g',
    appId: '1:94960442791:web:410e7ea2f4bd9edf002a82',
    messagingSenderId: '94960442791',
    projectId: 'findata-8b973',
    storageBucket: 'findata-8b973.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMD3W_xU8bfoOcgl1ChzTA1sCT_mQnI9g',
    appId: '1:94960442791:ios:571c6d4f07ff2993002a82',
    messagingSenderId: '94960442791',
    projectId: 'findata-8b973',
    storageBucket: 'findata-8b973.appspot.com',
  );
}
